doc: >
  This is a configuration file is used when setting up the minio server.
  You'll need these to log on to the admin console on http://s3-minio:9900 and create the access keys.

config:
  user: minio
  password: jazzword
  data_dir: /opt/freeds/data/minio
