doc: >
  This config contains the repos and folders to scan for notebooks in nbdeploy.

config:
  preseve_temp: false
  temp_dir: /tmp/nbdeploy
  bucket: notebooks
  repos:
    - name: pipe-dreams
      directories:
        - notebooks
